### ISSUE TITLE
setPosition doesn’t smoothly scroll

### ISSUE THREAD

**Issue by RicLeP** [ilyashubin/scrollbooster#16]
Is there a way to make setPosition smoothly scroll?

```
scroll() {
	this.scrollBooster.setPosition({
		x: this.scrollBooster.getUpdate().position.x += 200
	});
}
```

This is attached to a button that will scroll the content. I tried to maually set the translate:

```
scroll() {
	contentElement.style.transform = `translateX(${-data.position.x}px)`
}
```

But this gets overidden instantly and set back to the current position stored with ScollBooster.

**Comment by ManiakMill** [comment]
How to solve this problem?

**Comment by ilyashubin** [comment]
Hello! There is now method `scrollTo` in version 2 of the library for smooth scrolling to coordinate
