### ISSUE TITLE
Position problem.

### ISSUE THREAD

**Issue by ManiakMill** [ilyashubin/scrollbooster#17]
Hello! I work with your library and find some problems. When i use touch devices like a (iphone, ipad etc) scroll position not updated. All time back to start. How i should solved this problem. On your site demo all works perfect

**Comment by ilyashubin** [comment]
Hello! That is strange, however I cannot say anything specific without you code. Some online sandbox with example would be very useful

**Comment by ilyashubin** [comment]
Please let me know if the problem remains
I'm closing it for now

**Comment by ManiakMill** [comment]
Hello Thank you. Problem is solved

**Comment by square360-george** [comment]
What did you do to solve this issue? We are seeing the same thing happen and can not identify what is causing the scroll of the menu back to the star every time the mouse is released.
