### ISSUE TITLE
Horizontal scrolling with mouse wheel

### ISSUE THREAD

**Issue by strarsis** [ilyashubin/scrollbooster#19]
@ilyashubin: Is it possible to use your library to allow horizontal scrolling by mouse wheel?
This is currently only possible with JavaScript as browsers don't seem to native have this behaviour.

**Comment by ilyashubin** [comment]
Hello! Yeah, it is possible. If you scrolling with CSS only (`transform` property), you can use config like this:
```js
new ScrollBooster({
    viewport,
    content,
    direction: 'horizontal',
    emulateScroll: true,
    onUpdate: (state) => {
        content.style.transform = `translateX(${-state.position.x}px)`
    }
})
```

If you use native scrolling, scrolling is handled by browser itself:

``` js
new ScrollBooster({
  viewport,
  content,
  direction: 'horizontal',
  onUpdate: (state) => {
    viewport.scrollLeft = state.position.x;
  }
})
```

**Comment by strarsis** [comment]
@ilyashubin: Can I use with [simplebar](https://github.com/Grsmto/simplebar)?

And is it possible to make the scroll content [draggable](https://github.com/Grsmto/simplebar/issues/423) with `scrollbooster`.

**Comment by ilyashubin** [comment]
I think it is possible. Simplebar uses native browser scrolling, so there should not be problems. But I never tried, so cant say for sure
Let me know if they worked well together :)
