### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by minhtranite** [ilyashubin/scrollbooster#20]
Hi,

Could you add the changelog for V2 release ? Current I use v1 so just wonder is it ok to upgrade to v2 and what new in v2 ?

Thanks!

**Comment by ilyashubin** [comment]
Hello! Definitely a good idea. Here you go https://github.com/ilyashubin/scrollbooster/releases/tag/v2.0.0

**Comment by minhtranite** [comment]
Thank you so much!
