### ISSUE TITLE
right click

### ISSUE THREAD

**Issue by comiewcom** [ilyashubin/scrollbooster#25]
hello.
thank you for your great project!

I have a suggestion.
How about ignoring right-clicks?(contextmenu event)

If you right-click on the content, the content will always be dragged, even if you release the button.

I don't think there is any disadvantage to ignoring the contextmenu event.

I would be happy if you could consider it.

**Comment by bramdoppen** [comment]
Perhaps it's an idea to (also) store the mouse/touchevent which triggers the and include that data inside the object that shouldScroll returns.

Inside this function: `this.events.pointerdown = (event)`, the parameter 'event.button' will tell you which button (on the mouse) is pressed. (https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button)

**Comment by ilyashubin** [comment]
Hello! Yes, its a good idea to disable right click scrolling by default, thanks for suggestion
As for now this should do the trick:
```js
  new ScrollBooster({
    ...
    shouldScroll(state, event) {
      if (event.button === 2) {
        return false
      }
      return true
    }
  });
```

**Comment by ilyashubin** [comment]
In v2.2 it is now disabled by default
