### ISSUE TITLE
touch tap doesn't work

### ISSUE THREAD

**Issue by purplecandle** [ilyashubin/scrollbooster#26]
I have tab elements, and I made them scrollable. I can't change tabs because you made return in toucstart event.

**Comment by ilyashubin** [comment]
Hello! Can you please specify exact line of code with this `return`?

**Comment by purplecandle** [comment]
> Hello! Can you please specify exact line of code with this `return`?

event.preventDefault(). I don't know why do you prevent event action. What I want to tap on something that inside scrollable content?

**Comment by ilyashubin** [comment]
`event.preventDefault()` is there to prevent page scrolling on mobile devices.
You can handle manual taps inside `shouldScroll` handler (just return `false` if you tapped on some content that needs interaction)

**Comment by purplecandle** [comment]
> `event.preventDefault()` is there to prevent page scrolling on mobile devices.
> You can handle manual taps inside `shouldScroll` handler (just return `false` if you tapped on some content that needs interaction)

Oh, thanks a lot) I'm closing this issue because there's no any
