### ISSUE TITLE
Mac safari 10/11 version not working

### ISSUE THREAD

**Issue by BhanuChandraReddy** [ilyashubin/scrollbooster#29]
Hi Ilyashubin,

It's working well in Chrome, Firefox and safari 12+ but not in mac safari 10/11, facing issues with the package and my application is stable before adding this package. 

Even your reference website (https://ilyashubin.github.io/scrollbooster/) also not working in mac safari 10/11 - 
**Unexpected token '...'. Expected a property name.**

Please resolve the issue.

**Comment by ilyashubin** [comment]
Hello! I don't have access to those versions of Safari, so I cannot investigate this issue, sorry.
It may be helpful if you provide error stack trace or exact line of code where error occurs
Also, can you provide your library init code?

**Comment by ilyashubin** [comment]
I'm closing this for now, feel free to reopen if you get any info on this
