### ISSUE TITLE
Method scrollPosition

### ISSUE THREAD

**Issue by joaqib** [ilyashubin/scrollbooster#3]
Hi, first of all, great work!!
I was working with Scrollbooster and I just noticed that there could be a great addition
scrollPosition
where we could pass a coordinate and the container moves to it in a smooth manner
Similar to - window.scrollBy(x-coord, y-coord);
We are working on it, don't know if with the best perspective, but hopefully, we can show you guys something

**Comment by ilyashubin** [comment]
Thank you! Of course, you're welcome to contribute 👍 I think this would be quite useful
