### ISSUE TITLE
click event

### ISSUE THREAD

**Issue by hacknlove** [ilyashubin/scrollbooster#4]
it would be great to have some option to avoid clicks when scrolling.

It can be done manually, comparing coordinates in mousedown with coordinates in click, but I think it is a common use case, so I think an option would be better.

**Comment by ilyashubin** [comment]
Sorry for late reply and thank you for suggestion! Yes, you absolutely right, it is a common use case. I'll implement a click hook with event in it to decide if we need to prevent default or some other kind of logic.

**Comment by ilyashubin** [comment]
Added `onClick` hook.

**Comment by hacknlove** [comment]
I am a bit confused, I cannot tell the diference between a simple click and a click involved in a scroll

I am getting always  `isDragging: false, isRunning: true, isScrolling: false`  no matter what, even if i just click or I scroll.

**Comment by mbaumrucker** [comment]
+1 same issue here, I need to be able to determine if click is during dragging or not ... now there is no way to do this, which defeats the purpose of this plugin for me

**Comment by bobbyrenwick** [comment]
For anyone else having the same issue you can use `data.dragOffsetPosition` as a heuristic to know whether the click is involved in a drag or not.

I'm using the following to give a little leniency:

```js
onClick: (data, event) => {
    if (Math.abs(data.dragOffsetPosition.x) > 5) {
        event.stopPropagation();
    }
},
```

**Comment by SahilMepani** [comment]
Thanks bobby. You saved my day!

**Comment by tripeh** [comment]
Thanks Bobby! You saved my day too!

**Comment by sippapeg** [comment]
Thanks! tripeh  event.preventDefault(); It's work for me too. Good Job

**Comment by Kyfi** [comment]
This code helped me to prevent movig/user-selecting image inside link and also firing click event when you are only swiping.

`
Link tag
onDragStart={event => {
  event.preventDefault()
  event.stopPropagation()
}}
....
img tag
...
Link tag close
`
