### ISSUE TITLE
Missing option to choose between mouse and touch

### ISSUE THREAD

**Issue by seahorsepip** [ilyashubin/scrollbooster#7]
I'm missing a way to only enable scrollbooster for mouse or touch, currently I use the shouldScroll callback to only make it work with mouse events:

```
//Only use scrollbooster for mouse interaction
shouldScroll: (data, event) => {
        const isTouch = !!(event.touches && event.touches[0]);
        return !isTouch;
}
```

**Comment by ilyashubin** [comment]
Thank for suggestion, added `pointerMode` option
