### ISSUE TITLE
Jumpy behavior when dragging with mouse after scrolling with touchpad

### ISSUE THREAD

**Issue by seahorsepip** [ilyashubin/scrollbooster#8]
I've a horizontal scroll view that can be scrolled my touch, touchpad or by dragging with scrollbooster.
When the scroll view is scrolled using the touchpad and afterwards dragged by scrollbooster, I get jumpy behavior :/

Currently I've worked around it by updating the scrollbooster offset in the shouldScroll method:
```
//Jumpy behavior workaround
shouldScroll: () => {
        sb.setPosition({x: scrollView.scrollLeft});
        return true
}
```

**Comment by byman64** [comment]
I have the same isse, where I should add that? scrollbooster.js? Can you give me more details/line number

thx

**Comment by WagnerExpansiva** [comment]
@byman64 

mybe 

`sb.setPosition({x: viewport.scrollLeft});`

**Comment by ilyashubin** [comment]
Not sure I understand correctly. Is this issue still relevant on version 2.0?
Some online sandbox with example would be very useful

**Comment by ilyashubin** [comment]
I think this may be due to an open devtools
I'm closing this for now, please let me know if this issue still remains
